<?php
/***************************************************************
 * Extension Manager/Repository config file for ext: "bsd_accmgr"
 *
 * Auto generated by Extension Builder 2019-10-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pardot API',
	'description' => '',
	'category' => 'service',
	'author' => 'Andreas Sommer',
	'author_email' => 'sommer@belsignum.com',
	'state' => 'beta',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.0-10.4.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
